### ISSUE TITLE
ip2proxy module error rate is high

### ISSUE THREAD

**Issue by dpriscornic** [ip2location/ip2proxy-c#2]
Hello,

We are using ip2proxy-c with nginx build with https://github.com/ip2location/ip2proxy-nginx with PX4 database.

We tested with both shared_memory and cache_memory database loading options and the failure rate (C library returning IP2Proxy_is_proxy value -1) is high, 10 to 30 %. This happens randomly, apparently, meaning that the same IP gets the correct  IP2Proxy_is_proxy value and all the ip2proxy variables in 70 to 90 % of the cases and the error  IP2Proxy_is_proxy=-1 in the rest of the cases.

We tested under multiple loads, the rate is almost the same.
We tested on multiple configurations (4 CPU 8 GB RAM, 8 CPU 24 GB RAM) and the results are similar.

For all the tests mentioned in this issue I used PX4 version released on  December 06, 2018

The module and the nginx are built as rpms, I can provide the rpms if needed for testing if you cannot reproduce.

Test 1:

server: centos7 with nginx 1.13.12 build with ip2proxy and ip2location modules with 4  CPUs and 24 GB RAM
Calls from IP address: 52.44.56.77 (it should return IP2Proxy_is_proxy value 2)
rate: 500 req/second
result: IP2Proxy_is_proxy returns 2 for 70% of the calls, and -1 for 30% of the calls

Test 2:

server: centos7 with nginx 1.13.12 build with ip2proxy and ip2location modules with 4  CPUs and 24 GB RAM
Calls from IP address: 103.246.77.77 (it should return IP2Proxy_is_proxy value 0)
rate: 500 req/second
result: IP2Proxy_is_proxy returns 0 for 90% of the calls, and -1 for 10% of the calls

**Comment by ip2location-com** [comment]
I'm afraid that the library is not optimized for high rate query at this moment.
